# Generated by Django 4.2.5 on 2024-07-24 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LasFileModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("local_path", models.CharField(max_length=100000)),
                ("remote_download_url", models.URLField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_converted", "Not Converted"),
                            ("converting", "Converting"),
                            ("converted", "Converted"),
                        ],
                        default="not_converted",
                        max_length=100,
                    ),
                ),
                ("name", models.CharField(max_length=100000, unique=True)),
                ("downloaded", models.BooleanField(default=False)),
                ("deleted_from_local_path", models.BooleanField(default=False)),
            ],
        ),
    ]
