# Generated by Django 4.1.1 on 2024-07-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("las_files", "0006_alter_lasfilemodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lasfilemodel",
            name="remote_download_url",
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
